apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etcd-backup

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac-privileged-scc.yaml
  - configmap-etcd-backup-config.yaml
  - secret-etcd-backup-s3.yaml
  - cronjob-etcd-backup.yaml
  - prometheusrule-etcd-backup.yaml
